name: $(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
  - repository: self
    type: git
    ref: master

trigger:
  branches:
    include:
    - '*'  # default
  paths:
    include:
    - '*'  # default
  tags:
    include:
    - '*'  # default

# trigger: none
pr: # also allows branches and paths
  - '*' # default. These are PR target branches, e.g. master

stages:
- stage: First stage
  jobs:
  - job: job1
    displayName: Job 1
    strategy:
      matrix:
        ubuntu:
          imageName: ubuntu-latest
        macos:
          imageName: macOS-latest
        windows:
          imageName: windows-latest
    pool:
      name: Azure Pipelines
      vmImage: $(imageName)
    steps:
    - pwsh: 'Get-ChildItem Env:'
      displayName: Log Environment
      continueOnError: true
    - pwsh: echo '${{ convertToJson(variables) }}'
      displayName: Log variables
      continueOnError: true
    - pwsh: echo '${{ convertToJson(parameters) }}'
      displayName: Log parameters
      continueOnError: true
    - pwsh: echo '${{ convertToJson(System) }}'
      displayName: Log System
      continueOnError: true
    - pwsh: echo '${{ convertToJson(Pipeline) }}'
      displayName: Log Pipeline
      continueOnError: true
    - pwsh: echo '${{ convertToJson(Agent) }}'
      displayName: Log Agent
      continueOnError: true
    - pwsh: echo '${{ convertToJson(Build) }}'
      displayName: Log Build
      continueOnError: true
